services:
  service:
    build:
      context: .
      dockerfile: service/Dockerfile
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_ADDRESS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_MAX_OPEN_CONNECTION=${DB_MAX_OPEN_CONNECTION}
      - DB_MAX_OPEN_LIFE_TIME=${DB_MAX_OPEN_LIFE_TIME}
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  postgresql:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local